import json

# Simulated playlist entries generated by downloader.py for the Behance link
entries = [
  {"ext": "png", "vcodec": "image", "url": "http://img"},
  {"ext": "mp4", "vcodec": "video", "url": "http://vid", "formats": [{"ext": "mp4", "vcodec": "video"}]},
  {"ext": "gif", "vcodec": "image", "url": "http://gif"},
]

info = {"_type": "playlist", "entries": entries, "id": "123"}

is_playlist = True
is_image = False
is_mixed = False

if is_playlist:
    if info.get('id') == 'gallery':
        is_image = True
    else:
        entries_info = info.get('entries', [])
        if entries_info:
            has_video = False
            has_image = False
            for entry in entries_info:
                entry_formats = entry.get('formats', [])
                ext = entry.get('ext', '').lower()
                vcodec = entry.get('vcodec')
                if '?' in ext: ext = ext.split('?')[0]
                if not ext and entry.get('url'):
                    ext = entry['url'].split('.')[-1].split('?')[0][:4].lower()
                
                is_img = False
                if ext in ['jpg', 'jpeg', 'png', 'webp', 'gif'] or vcodec == 'image':
                    is_img = True
                    
                if entry_formats:
                    for f in entry_formats:
                        f_ext = f.get('ext', '').lower()
                        f_vcodec = f.get('vcodec')
                        if f_ext in ['mp4', 'webm', 'mkv', 'mov', 'avi', 'm4v', 'flv']:
                            is_img = False
                            break
                        if f_vcodec and f_vcodec not in ['image', 'none']:
                            is_img = False
                            break
                else:
                    if ext in ['mp4', 'webm', 'mkv', 'mov', 'avi', 'm4v', 'flv'] or (vcodec and vcodec not in ['image', 'none']):
                        is_img = False
                        
                if is_img:
                    has_image = True
                else:
                    has_video = True
            
            if has_image and not has_video:
                is_image = True
            elif has_image and has_video:
                is_mixed = True

print(f"is_image: {is_image}, is_mixed: {is_mixed}")
